#!/usr/bin/env node
var fs = require('fs');

if (process.argv.length < 3) {
	console.log('Too few arguments; please specify a profile');
	process.exit(2);
}

var profile = process.argv[2];
var profileFilePath = './packages/' + profile + '.package.json';

if (!fs.existsSync(profileFilePath)) {
	console.log('No file matching that profile exists (expected ', profileFilePath, ')');
	process.exit(1);
}

var matchingPackageFile = fs.readFileSync(profileFilePath);
fs.writeFileSync('./package.json', matchingPackageFile);
